In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
# from IPython.display import display, HTML

# CSS = """
# div.cell:nth-child(5) .output {
#     flex-direction: row;
# }
# """

# HTML('<style>{}</style>'.format(CSS))

In [21]:
import os,sys,inspect
import re
import csv
import importlib
import matplotlib.pyplot as plt
import pandas as pd
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)

In [22]:
from src.plot_utils import *
from src.dataset_getters import *
from src.create_basic_statistics_for_dataset import *

In [ ]:
SET = 'b'

In [ ]:
plot_kaggle_signals(5, SET)

In [ ]:
plot_kaggle_signals_by_label(5, SET, 'normal')

In [ ]:
#PLOT RANDOM FILES WITH 'EXTRASYSTOLE' LABEL
plot_kaggle_signals_by_label(5, SET, 'extrastole')

In [ ]:
#PLOT RANDOM FILES WITH 'EXTRASYSTOLE' LABEL
plot_kaggle_signals_by_label(5, 'a', 'extrahls')

In [ ]:
#PLOT RANDOM FILES WITH 'MURMUR' LABEL
plot_kaggle_signals_by_label(5, SET, 'murmur')

In [ ]:
create_dataframe_with_sampling_frequencies(SET)

In [ ]:
data = count_statistics_for_recording_lengths(SET)
# change outlier point symbols
plt.figure()
plt.title('recording lengths')
plt.boxplot(data, 0,'gD')

In [13]:
display(create_dataframe_for_sampling_frequencies('a', get_kaggle_audio_dir_path, 'kaggle').describe())
display(create_dataframe_for_sampling_frequencies('b', get_kaggle_audio_dir_path, 'kaggle').describe())

       kaggle sampling rates set_a
count                        124.0
mean                       44100.0
std                            0.0
min                        44100.0
25%                        44100.0
50%                        44100.0
75%                        44100.0
max                        44100.0

       kaggle sampling rates set_b
count                        461.0
mean                        4000.0
std                            0.0
min                         4000.0
25%                         4000.0
50%                         4000.0
75%                         4000.0
max                         4000.0

In [17]:
display(create_dataframe_for_sampling_frequencies('a', get_physionet_audio_dir_path, 'physio').describe())
display(create_dataframe_for_sampling_frequencies('b', get_physionet_audio_dir_path, 'physio').describe())
display(create_dataframe_for_sampling_frequencies('c', get_physionet_audio_dir_path, 'physio').describe())
display(create_dataframe_for_sampling_frequencies('d', get_physionet_audio_dir_path, 'physio').describe())
display(create_dataframe_for_sampling_frequencies('e', get_physionet_audio_dir_path, 'physio').describe())
display(create_dataframe_for_sampling_frequencies('f', get_physionet_audio_dir_path, 'physio').describe())

       physio sampling rates set_a
count                        409.0
mean                        2000.0
std                            0.0
min                         2000.0
25%                         2000.0
50%                         2000.0
75%                         2000.0
max                         2000.0

       physio sampling rates set_b
count                        490.0
mean                        2000.0
std                            0.0
min                         2000.0
25%                         2000.0
50%                         2000.0
75%                         2000.0
max                         2000.0

       physio sampling rates set_c
count                         31.0
mean                        2000.0
std                            0.0
min                         2000.0
25%                         2000.0
50%                         2000.0
75%                         2000.0
max                         2000.0

       physio sampling rates set_d
count                         55.0
mean                        2000.0
std                            0.0
min                         2000.0
25%                         2000.0
50%                         2000.0
75%                         2000.0
max                         2000.0

       physio sampling rates set_e
count                       2141.0
mean                        2000.0
std                            0.0
min                         2000.0
25%                         2000.0
50%                         2000.0
75%                         2000.0
max                         2000.0

       physio sampling rates set_f
count                        114.0
mean                        2000.0
std                            0.0
min                         2000.0
25%                         2000.0
50%                         2000.0
75%                         2000.0
max                         2000.0

In [32]:
display(create_dataframe_for_magnitude('a', get_physionet_audio_dir_path, 'physio').describe())

       physio magnitudes set_a
count             2.665622e+07
mean             -9.966789e-01
std               2.076770e+03
min              -3.276800e+04
25%              -3.480000e+02
50%               2.000000e+00
75%               3.490000e+02
max               3.276700e+04

In [ ]:
SET = 'b'
count_statistics_for_sampling_frequencies(SET).describe()

In [43]:
df['label'].value_counts()

-1    2575
 1     665
Name: label, dtype: int64